export const TYPES = {
  fire: require("../../assets/fire-type.png"),
  shadow: require("../../assets/shadow-type.png"),
  unknown: require("../../assets/unknown-type.png"),
  fairy: require("../../assets/fairy-type.png"),
  dark: require("../../assets/dark-type.png"),
  dragon: require("../../assets/dragon-type.png"),
  normal: require("../../assets/normal-type.png"),
  fighting: require("../../assets/fighting-type.png"),
  flying: require("../../assets/flying-type.png"),
  poison: require("../../assets/poison-type.png"),
  ground: require("../../assets/ground-type.png"),
  rock: require("../../assets/rock-type.png"),
  bug: require("../../assets/bug-type.png"),
  ghost: require("../../assets/ghost-type.png"),
  steel: require("../../assets/steel-type.png"),
  water: require("../../assets/water-type.png"),
  grass: require("../../assets/grass-type.png"),
  electric: require("../../assets/electric-type.png"),
  psychic: require("../../assets/psychic-type.png"),
  ice: require("../../assets/ice-type.png"),
}

